package com.example.heraapp.ui

import java.util.UUID

// A sealed class representing chat messages in the app
sealed class ChatMessage(open val id: String, open val message: String) {

    // Message sent by the user, with a default UUID as the ID
    data class UserMessage(override val message: String, override val id: String = UUID.randomUUID().toString()) : ChatMessage(id, message)

    // Message generated by the bot, also with a default UUID as the ID
    data class BotMessage(override val message: String, override val id: String = UUID.randomUUID().toString()) : ChatMessage(id, message)
}

